services:
  db:
    image: postgres:16
    container_name: rkdb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:4
    container_name: rkadminer
    ports:
      - "8080:8080"
    depends_on:
      - db

  app:
    build: ./app
    container_name: rkapp
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app
      - modeldata:/app/model
    command: ["python","-m","src.schedule"]
    # ↑ 常駐スケジューラ。手動実行する場合は runner を使う

volumes:
  dbdata:
  modeldata:
